name: docker-react
on: [push]

sudo: required
services:
  - docker

before_install:
  - docker build -t trantbatey/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trantbatey/docker-react npm run test
