name: docker-react
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      run: docker build -t trantbatey/docker-react-test -f Dockerfile.dev .
    - name: run docker test
      run: docker run -e CI=true trantbatey/docker-react-test npm run test

# .github/workflows/heroku-deploy.yml
  heroku-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t trantbatey/docker-react .
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
