name: docker-react
on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      run: docker build -t trantbatey/docker-react -f Dockerfile.dev .
    - name: run docker test
      run: docker run -e CI=true trantbatey/docker-react npm run test
